# Demo sample ONLY — fake placeholders
[Interface]
PrivateKey = CLIENT_PRIVATE_KEY_PLACEHOLDER
Address = 192.168.220.3/24
DNS = 192.168.220.1
MTU = 1280

[Peer]
PublicKey = SERVER_PUBLIC_KEY_PLACEHOLDER
PresharedKey = PRESHARED_KEY_PLACEHOLDER
AllowedIPs = 192.168.220.1/32, 10.200.0.0/14
Endpoint = 192.0.2.1:53254
PersistentKeepalive = 16
